project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of Omaha Bridges"
  author: "Lily Neneman"
  page-footer:
    left: "Copyright 2025, Lily Neneman"
  chapters:
    - ExecutiveSummary.qmd
    - Introduction.qmd
    - Methods.qmd
    - Results.qmd
    - Conclusion.qmd
    - references.qmd
  appendices:
    - index.qmd
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



