---
title: "Conclusion"
editor: visual
---

This report offers a good starting point for understanding the risks of bridge failure in Omaha. However, it is important to keep in mind that the data comes from public sources. While this data is reliable, the inspection methods and how often they inspect the bridges can vary. The data also looks at bridges in all of Nebraska, so it isn't always specific at the city level. It is also important to keep in mind a bridge collapse can't exactly be predicted, and this report only considers the likelihood based on their conditions. It gives us a good starting point on what poses us the most risk.

The analysis reveals that bridges classified as being in "poor" condition are a significant risk to the city, especially those that carry high traffic volumes. Bridges like US75 over J St, which carry more than 85,000 daily crossings, are an example of a high-risk structure that requires attention. The data indicated that the County System, particularly in areas like Douglas and Sarpy Counties, face the most threat, with higher percentage of poor-condition bridges and high traffic.

With that being said, it is clear that focusing on bridges in poor condition, especially those with heavy daily traffic, is critical for reducing risk to our city. These bridges should be prioritized for repairs and improvements. Additionally, while the year a bridge was built does not appear to significantly affect its current condition, ongoing maintenance is crucial for preventing problems in the future.

In conclusion, it is essential to be proactive with this information for the safety of Omaha. Using this data Omaha can reduce the likelihood of bridge failures and ensure continued safety.

## Recommendations

1.  Prioritize Bridges in Poor Condition with High Traffic: Bridges like US75 over J St, which carry high traffic volumes and are in poor condition, should be prioritized for immediate repairs as these structures pose the highest risk to public safety
2.  Focus on High-Risk Areas: Specific counties, such as Douglas and Sarpy, show a higher percentage of poor-condition bridges. These areas should be targeted.
3.  Invest in Regular Inspections: To improve the accuracy of the data on bridge safety, regular inspections should be conducted.
4.  Ongoing Maintenance: While the age of a bridge does not appear to directly impact the condition, the lack of regular maintenance can. All bridges, regardless of the year built should be regularly maintained to prevent any deterioration in the future.
